import type { Metadata } from "next";
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "LuxTime Website",
  description: "Generated by create next app",
  keywords: ["jewelry", "jewelry store", "jewelry online", "jewelry shop"],
};

export default function DefaultLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
